import type { BuyerRecord, FarmerProfile, BuyerProfile, PurchaseOrder } from './agri-types';

export const INITIAL_FARMER_PROFILE: FarmerProfile = {
  id: 'farmer-01',
  name: 'Ramesh Patel',
  village: 'Pimpalgaon Baswant',
  taluka: 'Niphad',
  district: 'Nashik',
  state: 'Maharashtra',
  preferredLanguage: 'Marathi / English',
  totalFarmlandAcres: 5.5,
  cultivatedAreaAcres: 4.0,
  soilType: 'Black Cotton Soil (Regur)',
  irrigationMethod: 'Drip Irrigation & Well',
  farmingMethod: 'Organic',
  postHarvestFacilities: ['Sorting/Grading', 'Packaging', 'Shade Drying'],
  sellingPreferences: {
    preferredBuyerType: 'Any',
    sellingRadiusKm: 50,
    minQuantityKg: 50,
    priority: 'Fastest Sale',
  },
  crops: [
    {
      id: 'crop-01',
      name: 'Spinach (Palak)',
      variety: 'All Green Hybrid',
      acreage: 0.5,
      growthStage: 'Ready for Harvest',
      expectedHarvestDate: 'Harvest in 1 Day',
      estimatedQtyKg: 200,
      category: 'Leafy Vegetable',
      perishableLevel: 'HIGH',
      qualityGrade: 'Grade A Export',
      freshnessScore: 98,
      status: 'Harvesting',
    },
    {
      id: 'crop-02',
      name: 'Desi Tomato',
      variety: 'Pusa Ruby',
      acreage: 1.5,
      growthStage: 'Fruiting / Ripening',
      expectedHarvestDate: 'Harvest in 5 Days',
      estimatedQtyKg: 1500,
      category: 'Fruit',
      perishableLevel: 'MEDIUM',
      qualityGrade: 'Grade A Processing',
      freshnessScore: 94,
      status: 'Ready Soon',
    },
    {
      id: 'crop-03',
      name: 'Alphonso Mango',
      variety: 'Ratnagiri Hapus',
      acreage: 2.0,
      growthStage: 'Mature Fruit',
      expectedHarvestDate: 'Harvest in 10 Days',
      estimatedQtyKg: 3000,
      category: 'Fruit',
      perishableLevel: 'MEDIUM',
      qualityGrade: 'Grade A Export',
      freshnessScore: 96,
      status: 'Planted',
    },
  ],
};

export const MOCK_BUYERS: BuyerRecord[] = [
  {
    id: 'buyer-01',
    name: 'Nashik Fresh Agro Mart',
    type: 'Retailer',
    location: 'Niphad Road, Nashik',
    district: 'Nashik',
    state: 'Maharashtra',
    distanceKm: 8,
    cropsAccepted: ['Spinach (Palak)', 'Coriander', 'Methi', 'Desi Tomato', 'Onion'],
    qualityRequirements: 'Grade A Freshness, No Wilting / Blemish',
    minQuantityKg: 50,
    maxQuantityKg: 500,
    procurementRadiusKm: 25,
    verified: true,
    contactPhone: '+91 98220 11234',
    contactEmail: 'procure@nashikfresh.in',
    buyingPricePerKg: 24,
  },
  {
    id: 'buyer-02',
    name: 'Sahyadri Farmers Producer Co.',
    type: 'Aggregator',
    location: 'Mohadi, Dindori, Nashik',
    district: 'Nashik',
    state: 'Maharashtra',
    distanceKm: 14,
    cropsAccepted: ['Spinach (Palak)', 'Desi Tomato', 'Alphonso Mango', 'Grapes', 'Onion'],
    qualityRequirements: 'Sorted & Graded Produce, Low Pesticide Residue',
    minQuantityKg: 100,
    maxQuantityKg: 5000,
    processingType: 'Packhouse & Cold Chain Export',
    procurementRadiusKm: 60,
    verified: true,
    contactPhone: '+91 2557 234500',
    contactEmail: 'sahyadri@farmproduce.co.in',
    buyingPricePerKg: 22,
  },
  {
    id: 'buyer-03',
    name: 'MahaTomato Pulp & Sauce Processing Unit',
    type: 'Food Processor',
    location: 'MIDC Ambad, Nashik',
    district: 'Nashik',
    state: 'Maharashtra',
    distanceKm: 22,
    cropsAccepted: ['Desi Tomato', 'Tomato'],
    qualityRequirements: 'High Soluble Solids (>4.5 Brix), Deep Red Color',
    minQuantityKg: 500,
    maxQuantityKg: 10000,
    processingType: 'Tomato Ketchup, Puree & Concentrates',
    procurementRadiusKm: 80,
    verified: true,
    contactPhone: '+91 94239 88120',
    contactEmail: 'raw@mahatomato.com',
    buyingPricePerKg: 16,
  },
  {
    id: 'buyer-04',
    name: 'GreenBite Restaurant Chain',
    type: 'Restaurant',
    location: 'College Road, Nashik',
    district: 'Nashik',
    state: 'Maharashtra',
    distanceKm: 18,
    cropsAccepted: ['Spinach (Palak)', 'Coriander', 'Methi', 'Desi Tomato', 'Potato'],
    qualityRequirements: 'Strict Organic, Fresh Daily Morning Delivery',
    minQuantityKg: 30,
    maxQuantityKg: 150,
    procurementRadiusKm: 30,
    verified: true,
    contactPhone: '+91 98901 44556',
    contactEmail: 'kitchen@greenbite.in',
    buyingPricePerKg: 28,
  },
  {
    id: 'buyer-05',
    name: 'Apex Fruit Juices & Canning Ltd.',
    type: 'Food Processor',
    location: 'Verna Industrial Estate, Goa / Konkan',
    district: 'Ratnagiri',
    state: 'Maharashtra',
    distanceKm: 120,
    cropsAccepted: ['Alphonso Mango', 'Mango', 'Banana', 'Guava'],
    qualityRequirements: 'High Sugar Content (>16 Brix), Pulp Yield Suitable',
    minQuantityKg: 1000,
    maxQuantityKg: 20000,
    processingType: 'Mango Pulp, Canning & Nectars',
    procurementRadiusKm: 200,
    verified: true,
    contactPhone: '+91 97654 33210',
    contactEmail: 'procurement@apexfoods.com',
    buyingPricePerKg: 85,
  },
  {
    id: 'buyer-06',
    name: 'Pimpalgaon Agricultural Produce Market (APMC)',
    type: 'Wholesaler',
    location: 'Pimpalgaon Baswant',
    district: 'Nashik',
    state: 'Maharashtra',
    distanceKm: 3,
    cropsAccepted: ['Spinach (Palak)', 'Desi Tomato', 'Onion', 'Wheat', 'Rice', 'Potato'],
    qualityRequirements: 'Standard Commercial Grade',
    minQuantityKg: 100,
    maxQuantityKg: 50000,
    procurementRadiusKm: 15,
    verified: true,
    contactPhone: '+91 2554 221009',
    contactEmail: 'apmc@pimpalgaon.gov.in',
    buyingPricePerKg: 20,
  },
];

export const INITIAL_BUYER_PROFILE: BuyerProfile = {
  id: 'buyer-user-01',
  companyName: 'Sahyadri Farmers Producer Co.',
  contactPerson: 'Vikram Shinde (Procurement Officer)',
  buyerType: 'Food Processor',
  villageOrLocality: 'Mohadi, Dindori',
  district: 'Nashik',
  state: 'Maharashtra',
  procurementRadiusKm: 60,
  targetCrops: ['Spinach (Palak)', 'Desi Tomato', 'Alphonso Mango', 'Sona Masoori Rice'],
  qualitySpecification: 'Grade A Freshness, Low Residue, High Brix/Soluble Solids',
  minQtyKg: 100,
  maxQtyKg: 5000,
  buyingPricePerKgINR: 24,
  verified: true,
  phone: '+91 2557 234500',
  email: 'procure@sahyadrifoods.com',
};

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po-101',
    cropId: 'crop-01',
    cropName: 'Spinach (Palak)',
    farmerName: 'Ramesh Patel',
    farmerLocation: 'Pimpalgaon Baswant, Nashik',
    buyerName: 'Sahyadri Farmers Producer Co.',
    buyerType: 'Food Processor',
    quantityKg: 200,
    offeredPricePerKg: 24,
    totalAmountINR: 4800,
    status: 'PENDING',
    orderDate: '2026-08-29',
    deliveryDate: '2026-08-30',
  },
  {
    id: 'po-102',
    cropId: 'crop-02',
    cropName: 'Desi Tomato',
    farmerName: 'Ramesh Patel',
    farmerLocation: 'Pimpalgaon Baswant, Nashik',
    buyerName: 'MahaTomato Pulp Unit',
    buyerType: 'Food Processor',
    quantityKg: 1000,
    offeredPricePerKg: 18,
    totalAmountINR: 18000,
    status: 'ACCEPTED',
    orderDate: '2026-08-28',
    deliveryDate: '2026-09-02',
  },
];
